window.MathJax = {
    tex: {
      inlineMath: [['$', '$'], ['\\(', '\\)']],
      displayMath: [['$$','$$'], ['\\[','\\]']],
      macros: {
        abs: ["{\\lvert #1 \\rvert}", 1],
        N: "{\\mathbb{N}}",
        C: "{\\mathbb{C}}",
        CC:"{\\mathbb{C}}",
        FF:"{\\mathbb{F}}",
        ZZ:"{\\mathbb{Z}}",
        NN:"{\\mathbb{N}}",
        RR:"{\\mathbb{R}}",
        G: "{\\mathbb{G}}",
        A: "{\\mathbb{A}}",
        QQ: "{\\mathbb{Q}}",
        Q: "{\\mathbb{Q}}",
        Z: "{\\mathbb{Z}}",
        K: "{\\mathbf{K}}",
        R: "{\\mathbb{R}}",
        Sch: "{\\mathbb{S}}",
        cM: "{\\mathcal{M}}",
        cB: "{\\mathcal{B}}",
        cO: "{\\mathcal{O}}",
        lineq: "{\\mathrel{\\overset{\\mathrm{lin}}{\\sim}}}",
        mQ: "{\\mathcal{Q}}",
        mS: "{\\mathcal{S}}",
        mR: "{\\mathcal{R}}",
        ko: "{\\mathcal{O}}",
        ke: "{\\mathcal{E}}",
        mF: "{\\mathcal{F}}",
        sod: ["{\\langle #1 \\rangle}", 1],
        PP: "{\\mathbb{P}}",
        mbP: "{\\mathbb{P}}",
        KK: "{\\mathbb{K}}",
        zt: "{\\widehat{Z}}",
        E: "{\\mathcal{E}}",
        mU: "{\\mathcal{U}}",
        mL: "{\\mathcal{L}}",
        tW: "{\\widetilde{W}}",
        tS: "{\\widetilde{S}}",
        tV: "{\\widetilde{V}}",
        hN: "{\\widehat{N}}",
        of: "{\\mathcal{O}}",
        h: "{\\mathcal{H}}",
        F: "{\\mathcal{F}}",
        id: "{\\mathcal{I}}",
        de: "{\\partial}",
        canc: "{\\#}",
        debar: "{\\bar{\\partial}}",
        smat: ["{\\begin{smallmatrix} #1 & #2 \\\\ #3 & #4 \\end{smallmatrix}}", 4],
        mat: ["{\\begin{pmatrix} #1 & #2 \\\\ #3 & #4 \\end{pmatrix}}", 4],
        vet: ["{\\begin{smallmatrix} #1 \\\\ #2 \\end{smallmatrix}}", 2],
        W: "{\\bigwedge}",
        T: "{\\Theta}",
        s: "{\\mathfrak{sl}}",
        Db: "{D^{\\mathrm{b}}}",
        Proj: "{\\mathrm{Proj}}",
        I: "{\\mathrm{I}}",
        II: "{\\mathrm{II}}",
        IV: "{\\mathrm{IV}}",
        contr: "{\\lrcorner}",
        Ann: "{\\mathrm{Ann}}",
        D: "{\\mathrm{D}}",
        im: "{\\mathrm{Im}}",
        prim: "{\\mathrm{prim}}",
        HH: "{\\mathrm{HH}}",
        Pf: "{\\mathrm{Pf}}",
        Spec: "{\\mathrm{Spec}}",
        Ext: "{\\mathrm{Ext}}",
        tr: "{\\mathrm{tr}}",
        End: "{\\mathrm{End}}",
        llog: "{\\mathrm{log}}",
        Ker: "{\\mathrm{Ker}}",
        Id: "{\\mathrm{Id}}",
        GL: "{\\mathrm{GL}}",
        sort: "{\\mathrm{sort}}",
        Cok: "{\\mathrm{coKer}}",
        dd: "{\\mathrm{d}}",
        Res: "{\\mathrm{Res}}",
        Sym: "{\\mathrm{Sym}}",
        ddim: "{\\mathrm{dim}}",
        Gr: "{\\mathrm{Gr}}",
        OGr: "{\\mathrm{OGr}}",
        SGr: "{\\mathrm{SGr}}",
        Hom: "{\\mathrm{Hom}}",
        ddeg: "{\\mathrm{deg}}",
        HP: "{\\mathrm{HP}}",
        var: "{\\mathrm{var}}",
        van: "{\\mathrm{van}}",
        codim: "{\\mathrm{codim}}",
        Co: "{\\mathrm{C}}",
        TT: "{T_1}",
        Ml: "{S_2\\,Gr}",
        al: "{\\alpha}",
        into: "{\\hookrightarrow}",
        eorb: "{e_{\\mathrm{orb}}}",
        corb: "{c_{\\mathrm{orb}}}",
        coker: "{\\mathrm{coker}}",
        corbn: "{c_{n,\\mathrm{orb}}}",
        gen: "{\\mathrm{gen}}",
        Xbar: "{\\overline{X}}",
        Ybar: "{\\overline{Y}}",
        IIone: "{\\mathrm{II}_1}",
        rM: "{\\mathrm{M}}",
        rV: "{\\mathrm{V}}",
        tf: "{3\\text{-}fold}",
        wGr: "{w\\Gr}",
        wP: "{w\\P}",
        grdb: "{\\textsc{Grdb}}",
        car: "{\\mathrm{char}}",
        phiv: "{\\varphi}",
        llbracket: "\\lbrack\\!\\lbrack",
        rrbracket: "\\rbrack\\!\\rbrack",
        pow: ["\\llbracket #1 \\rrbracket", 1],
        epsi: "\\varepsilon"
      }
    }
  };
 
  